# Generated by Django 4.2.4 on 2023-08-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('major', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.TextField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
