# Generated by Django 4.2.4 on 2023-09-06 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
